name: Api

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:
   inputs:
      run-passing:
        type: boolean
        description: set to true to run the passing test
        default: true

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
   
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: run cucumber test 🔧
        run: chmod +x gradlew && ./gradlew test -Dcucumber.options="--tags @Api"
        if: ( ${{github.event.inputs.run-passing}} == true )
        continue-on-error: true

       - name: run cucumber test 🔧
        run: chmod +x gradlew && ./gradlew test -Dcucumber.options="--tags @Api-failing"
        if: ( ${{github.event.inputs.run-passing}} == false )
        continue-on-error: true

      - name: artifact cucumber-report.json
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-report
          path: build/cucumber-reports/cucumber-report.json

     

     