name: Api

on:
  pull_request:
    branches: [main]

  workflow_dispatch:
   inputs:
      run-passing:
        type: boolean
        description: 'run passing test'     
        required: false
        default: 'true'

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
   
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          
      - name: run passing cucumber test 🔧
        if: ${{github.event.inputs.run-passing == 'true' }}
        run: echo hehe
          
#       - if: ( ${{github.event.inputs.run-passing}} == 'true' )
#         name: run passing cucumber test 🔧
#         run: chmod +x gradlew && ./gradlew test -Dcucumber.options="--tags @Api"
#         continue-on-error: true
        
#       - if: ( ${{github.event.inputs.run-passing}} == 'false' )
#         name: run failing cucumber test 🔧
#         run: chmod +x gradlew && ./gradlew test -Dcucumber.options="--tags @Api-failing"
#         continue-on-error: true

#       - name: artifact cucumber-report.json
#         uses: actions/upload-artifact@v2
#         with:
#           name: cucumber-report
#           path: build/cucumber-reports/cucumber-report.json

     

     
