name: Api

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
   
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: run cucumber test 🔧
        run: chmod +x gradlew && ./gradlew test -Dcucumber.options="--tags @Api"
        continue-on-error: true

      - name: artifact cucumber-report.json
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-report
          path: build/cucumber-reports/cucumber-report.json

     

     