name: Belly

on:
  push:
    branches: [child-workflows]
  pull_request:
    branches: [main]

  workflow_dispatch:
    inputs:
      run-failing-scenario:
        type: boolean
        description: 'run failing belly scenario'     
        required: false
        default: true

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    env:
      REGION: "ap-southeast-2"
      S3_BUCKET: "ctaas-enterprise-poc/${{github.repository}}/${{github.workflow}}/${{github.run_number}}"
      S3_LATEST_RUN: "ctaas-enterprise-poc/${{github.repository}}/${{github.workflow}}/lastCompletedBuild"
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: run cucumber test 🔧
        if: ${{ github.event.inputs.run-failing-scenario }}
        run: chmod +x gradlew && ./gradlew test -Dcucumber.options="--tags @Belly"
        continue-on-error: true

      - name: skip failing test 🔧
        if: ${{ !github.event.inputs.run-failing-scenario }}
        run: chmod +x gradlew && ./gradlew test -Dcucumber.options="--tags @Belly --tags ~@Failing-scenario"
        continue-on-error: true

      - name: artifact cucumber-report.json
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-report
          path: build/cucumber-reports/cucumber-report.json

      - name: Update reports
        run: >
          gradle updateReports --reportUrl="https://s3-${{env.REGION}}.amazonaws.com/${{env.S3_BUCKET}}"
          --githubUrl="https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"

      - name: AWS configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Upload results to S3
        run: |
          cd build/cucumber-reports/cucumber-html-reports
          aws s3 sync . s3://${{ env.S3_BUCKET }} --no-progress --delete --exclude "html/"
          echo Updating latest run folder
          aws s3 sync s3://${{ env.S3_BUCKET }} s3://${{ env.S3_LATEST_RUN }} --no-progress --delete --exclude "html/"

      - name: Log report URLs
        run: |
          echo "Aggregate report: https://s3-${{env.REGION}}.amazonaws.com/${{env.S3_BUCKET}}/cucumber-results-agg-test-results.html"
          echo "Overview report: https://s3-${{env.REGION}}.amazonaws.com/${{env.S3_BUCKET}}/overview-features.html"